#!/usr/bin/env bash
# Bash script that displays the PID, along with the process name,
pids=$(pgrep "bash")
for pid in $pids; do
    process_name=$(ps -o comm= -p "$pid")
    echo "$pid $process_name"
done
