#!/bin/bash
#Install nginx on a server
sudo apt-get -y update

# Install Nginx
sudo apt-get -y install  nginx
sudo ufw app list

# Create a default Nginx configuration file
echo "server {
    listen 80;
    location / {
        echo 'Hello World!';
    }
}" > /etc/nginx/sites-available/default

# Test the Nginx configuration for syntax errors
if nginx -t | grep -q "syntax is okay"; then
    # Reload Nginx without using systemctl
    kill -s HUP "$(cat /var/run/nginx.pid)"
    echo "Nginx has been configured and reloaded successfully."
else
    echo "Nginx configuration has errors. Please check the configuration file."
fi
