#!/usr/bin/env bash
# Script that configures a new Ubuntu machine

sudo apt-get -y update
sudo apt-get -y install nginx
sudo sh -c 'echo "Hello World!" > /var/www/html/index.html'
sudo sh -c 'echo "Ceci n'\''est pas une page" > /var/www/html/error.html'
echo "server {
    listen 80;
    listen [::]:80 default_server;
    root   /etc/nginx/html;
    index  index.html;
    error 404 /error.html;
    location /redirect_me {
        return 301 https://google.com;
    }
}" > /etc/nginx/sites-available/default
sudo service nginx start