#!/usr/bin/env bash
#configures a new Ubuntu machine nginx
apt-get update
apt-get install --no-install-recommends software-properties-common
add-apt-repository ppa:vbernat/haproxy-2.8-y
apt-get update
apt-get install haproxy=2.8.\* -y
echo "frontend web-front
        bind *:80
        default_backend web-backend

backend web-backend
        balance roundrobin
        server 224417-web-01	100.26.246.25 check
        server 224417-web-02	100.25.23.198	 check
" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy start