#!/usr/bin/env bash
# Script that configures HAproxy

# Install software-properties-common without prompting
sudo apt-get install --no-install-recommends -y software-properties-common

# Add the HAProxy PPA repository without prompting
echo | sudo add-apt-repository ppa:vbernat/haproxy-2.8

# Update and install HAProxy 2.8 without prompting
sudo apt-get update
sudo apt-get install -y haproxy=2.8.*

# Backup the existing HAProxy configuration
sudo mv /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.backup

# Create a new HAProxy configuration using tee without prompting
sudo tee /etc/haproxy/haproxy.cfg > /dev/null <<EOF
frontend http_front
  bind *:80
  mode http
  default_backend web-backend

backend web-backend
  mode http
  balance roundrobin
  server 224417-web-01 100.26.246.25 check
  server 224417-web-02 100.25.23.198 check
EOF

# Enable HAProxy without prompting
sudo sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy

# Restart HAProxy without prompting
sudo service haproxy restart
