#!/usr/bin/env bash
# Function to handle SIGTERM and SIGQUIT signals

function cleanup() {
    echo "I hate the kill command"
    rm -f /var/run/myscript.pid
    exit 0
}

# Function to handle SIGINT signal
function handle_sigint() {
    echo "Y U no love me?!"
}

# Function to handle SIGTERM signal
function handle_sigterm() {
    echo "I hate the kill command"
}

# Register signal handlers
trap cleanup SIGQUIT SIGTERM
trap handle_sigint SIGINT

# Save the PID to the file
echo $$ > /var/run/myscript.pid

# Infinite loop

while true; do
    echo "To infinity and beyond indefinitely"
    sleep 1
done
