#!/usr/bin/env bash
# Function to handle SIGTERM and SIGQUIT signals
function cleanup() {
    echo "I hate the kill command"
    rm -f /var/run/myscript.pid
    exit 0
}
function handle_sigint() {
    echo "Y U no love me?!"
}
function handle_sigterm() {
    echo "I hate the kill command"
}
trap cleanup SIGQUIT SIGTERM
trap handle_sigint SIGINT
echo $$ > /var/run/myscript.pid
while true; do
    echo "To infinity and beyond indefinitely"
    sleep 1
done
