#!/usr/bin/env bash
# Define the file path

file="/etc/passwd"
if [ ! -f "$file" ]; then
    echo "Error: $file does not exist or is not a regular file."
    exit 1
fi

while IFS= read -r line; do
    echo "$line"
done < "$file"
