#!/usr/bin/env bash
# Define the file path
file="/etc/passwd"

if [ ! -f "$file" ]; then
    echo "Error: $file does not exist or is not a regular file."
    exit 1
fi

while IFS=: read -r username password groupid user_info home_directory command_shell; do
    echo "The user $username is part of the $groupid gang, lives in $home_directory and rides $command_shell. $username's place is protected by the passcode $password, more info about the user here: $username"
done < "$file"


