#!/usr/bin/env bash
# Check if the apache-access.log file exists
if [ ! -f "apache-access.log" ]; then
    echo "Error: The 'apache-access.log' file is missing. Please download and place it in the same directory as this script."
    exit 1
fi

awk '{ print $1, $9 }' apache-access.log | sort | uniq -c | sort -nr | awk '{ print $1, $2, $3 }'
