#!/usr/bin/env bash
#Does this
x=1
y=0
while [ $x -lt 60 ] && [ $y -le 12 ]
do
    if [ $x -eq 1 ];then
    echo "Hour: $y"
    fi
    echo "$x"
    x=$((x + 1))
    if [ $x -eq 60 ];then
    y=$((y + 1))
    x=1
    fi


done
