#!/usr/bin/env bash
# Displays all active IPv4 IPs on the machine it's executed on.

# Get all IP addresses associated with the machine
ip_address=$(hostname -I)

# Split the IP addresses into an array
ip_addresses=("${ip_address//" "/ }")

# Loop through each IP address
for ip in "${ip_addresses[@]}"; do
    # Use grep with a regular expression to match IPv4 addresses
    if echo "$ip" | grep -qE '^(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$'; then
        printf "%s\n" "$ip"
    fi
done
