#!/usr/bin/env bash
#displays all active IPv4 IPs on the machine it’s executed on.
ip_address=$(hostname -I)
ip_addresses=("${ip_address//" "/ }")
for ip in "${ip_addresses[@]}";
do
    printf "%s\n" "$ip"
done
